assetsInCome.page.rowCount=3

server.qrCode.path=/usr/local/webapp/cms/front/qrCodeImg
request.qrCode.path=/front/qrCodeImg

#wxRedirectUrl
wxHost=http://192.168.8.171:17811
#pcRedirectUrl
pcHost=http://192.168.8.171:17846

wxFundElePicPre=/usr/local/webapp/cmwa-wx-webapp
wxFundElePic=/WeixinService/business/fundPic/

#mailPath
toMailPath=ex-chenbq@cmfchina.com
ccMailPath=ex-longyh@cmfchina.com

#resetLPassWord  unit: second
resetLPWGapTime = 60


#sino activity config start
## get jd card param
cmwa.wx.sino.appKey=NPu4q6nBVE5R2VGo
cmwa.wx.sino.appId=378cb034df
cmwa.wx.sino.tradeRequestUrl=http://119.23.246.33:8082/charge-api/trade/ecoupon
cmwa.wx.sino.queryRequestUrl=http://119.23.246.33:8082/charge-api/trade/getCardInfo
cmwa.wx.sino.award.decryptKey=waerere2132323
cmwa.wx.sino.award.agtPhone=18664940068
cmwa.wx.sino.award.tradePwd=e3ceb5881a0a1fdaad01296d7554868d


## sinosafe param
cmwa.wx.sino.redirectUrl=http://qmyb.sinosafe.com.cn/api/api_cmb.php
cmwa.wx.sion.send.secret=ed5ca131520e520b7480e4283ebe8336
cmwa.wx.sion.redirect.secret=hacmc20181010


## thead execure param
cmwa.wx.sino.resendthred.excute=OFF
# sino activity config end