jdbc.key=8a!2e4b4%1b6e2&ba5.-011b?720f-=+



#waecweixinuser
jdbc.ecweixinuser.driverClassName=oracle.jdbc.driver.OracleDriver
jdbc.ecweixinuser.url=jdbc:oracle:thin:@192.168.8.129:1521:cmwadev01
jdbc.ecweixinuser.username=waecweixinuser
#9BD9ED7B142F98C5C1046166447C4B56=cmf+2011
jdbc.ecweixinuser.password=9BD9ED7B142F98C5C1046166447C4B56
jdbc.ecweixinuser.acquireIncrement=1
jdbc.ecweixinuser.maxIdleTime=20000
jdbc.ecweixinuser.maxPoolSize=2
jdbc.ecweixinuser.minPoolSize=2
jdbc.ecweixinuser.initialPoolSize=2
jdbc.ecweixinuser.checkoutTimeout=20000


#waecserviceuser
jdbc.ecserviceuser.driverClassName=oracle.jdbc.driver.OracleDriver
jdbc.ecserviceuser.url=jdbc:oracle:thin:@192.168.8.129:1521:cmwadev01
jdbc.ecserviceuser.username=waecuser
#9BD9ED7B142F98C5C1046166447C4B56=cmf+2011
jdbc.ecserviceuser.password=9BD9ED7B142F98C5C1046166447C4B56
jdbc.ecserviceuser.acquireIncrement=1
jdbc.ecserviceuser.maxIdleTime=20000
jdbc.ecserviceuser.maxPoolSize=2
jdbc.ecserviceuser.minPoolSize=2
jdbc.ecserviceuser.initialPoolSize=2
jdbc.ecserviceuser.checkoutTimeout=20000

#waecserviceuser
jdbc.eclog.driverClassName=oracle.jdbc.driver.OracleDriver
jdbc.eclog.url=jdbc:oracle:thin:@192.168.8.129:1521:cmwadev01
jdbc.eclog.username=waecuser
#9BD9ED7B142F98C5C1046166447C4B56=cmf+2011
jdbc.eclog.password=9BD9ED7B142F98C5C1046166447C4B56
jdbc.eclog.acquireIncrement=1
jdbc.eclog.maxIdleTime=3600
jdbc.eclog.maxPoolSize=2
jdbc.eclog.minPoolSize=2
jdbc.eclog.initialPoolSize=2
jdbc.eclog.checkoutTimeout=20000

#waecuser ec db 
jdbc.waecuser.driverClassName=oracle.jdbc.driver.OracleDriver
jdbc.waecuser.url=jdbc:oracle:thin:@192.168.8.129:1521:cmwadev01
jdbc.waecuser.username=waecuser
#9BD9ED7B142F98C5C1046166447C4B56=cmf+2011
jdbc.waecuser.password=9BD9ED7B142F98C5C1046166447C4B56
jdbc.waecuser.acquireIncrement=1
jdbc.waecuser.maxIdleTime=3600
jdbc.waecuser.maxPoolSize=2
jdbc.waecuser.minPoolSize=2
jdbc.waecuser.initialPoolSize=2
jdbc.waecuser.checkoutTimeout=20000
