#test2
#wx.config.token=
#wx.config.name=gh_07f2360bf03a
#wx.config.appid=wx6fbdf42f5ed9a8af
#wx.config.secret=25579ac8f551c8fb013cd49b33bc5633

#test1
wx.config.token=cmfchina2013
wx.config.name=gh_e7065a8ea162
wx.config.appid=wx364de7d5ff553336
wx.config.secret=84f471cd6638085f13dcf4091ecf2eef
wx.config.socketIP=192.168.9.227
wx.config.socketPort=1880
wx.config.wxHost=http://wxtest1.cmwachina.com/
wx.config.bindAccUrl=http://wxtest1.cmwachina.com/WeixinService/weixinLogin/login.shtml
wx.config.registerUrl=http://wxtest1.cmwachina.com/WeixinService/weixinLogin/register.shtml
wx.config.fundCenterUrl=http://wxtest1.cmwachina.com/WeixinService/business/query/fundList.shtml?item=div3