<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

	<modelVersion>4.0.0</modelVersion>
	<groupId>com.cmwa.ec.weixin.web</groupId>
	<version>2.01.000</version>
	<packaging>jar</packaging>
	<name>wx-webapp</name>
	<repositories>
		<repository>
			<id>central</id>
			<name>Central</name>
			<url>http://192.168.8.159:8081/nexus/content/groups/public/</url>
			<releases>
			</releases>
			<snapshots>
			</snapshots>
		</repository>

		<repository>
			<id>apache-snapshots</id>
			<name>Apache-snapshots</name>
			<url>http://192.168.8.159:8081/nexus/content/groups/public/</url>
			<releases>
			</releases>
			<snapshots>
			</snapshots>
		</repository>

	</repositories>

	<pluginRepositories>
		<pluginRepository>
			<id>central</id>
			<name>Central</name>
			<url>http://192.168.8.159:8081/nexus/content/groups/public/</url>
			<releases>
			</releases>
			<snapshots>
			</snapshots>
		</pluginRepository>

		<pluginRepository>
			<id>apache-snapshots</id>
			<name>Apache-snapshots</name>
			<url>http://192.168.8.159:8081/nexus/content/groups/public/</url>
			<releases>
			</releases>
			<snapshots>
			</snapshots>
		</pluginRepository>


	</pluginRepositories>

	<properties>
		<!--  <target.path>/usr/local/weixin/webapp</target.path> -->
		<target.path>${targetDir}</target.path>
		<!-- <target.path>D:/software/resin-4.0.0-wxapp/webapps</target.path> -->
		<jetty.version>7.6.11.v20130520</jetty.version>
		<spring.version>3.2.3.RELEASE</spring.version>
		<jetty.version>7.6.11.v20130520</jetty.version>
		<slf4j.version>1.7.5</slf4j.version>
		<logback.version>1.0.13</logback.version>
		<project.build.sourceEncoding>GBK</project.build.sourceEncoding>
		<jdk.version>1.6</jdk.version>
	</properties>


	<dependencies>
		<dependency>
			<groupId>com.cmf.ec</groupId>
			<artifactId>cmf-rpc</artifactId>
			<version>1.0.2</version>
			<exclusions>
				<exclusion>
					<groupId>org.springframework</groupId>
					<artifactId>spring</artifactId>
				</exclusion>
				<exclusion>
					<groupId>javax.servlet</groupId>
					<artifactId>servlet-api</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.slf4j</groupId>
					<artifactId>slf4j-jdk14</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<!-- mybatis start -->
		<dependency>
			<groupId>org.mybatis</groupId>
			<artifactId>mybatis</artifactId>
			<version>3.2.7</version>
			<exclusions>
				<exclusion>
					<groupId>*</groupId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.mybatis</groupId>
			<artifactId>mybatis-spring</artifactId>
			<version>1.2.2</version>
			<exclusions>
				<exclusion>
					<groupId>*</groupId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>commons-fileupload</groupId>
			<artifactId>commons-fileupload</artifactId>
			<version>1.3.1</version>
		</dependency>
		
		<dependency>
			<groupId>org.apache.poi</groupId>
			<artifactId>poi-excelant</artifactId>
			<version>3.9</version>
		</dependency>
		
		<dependency>
			<groupId>org.apache.poi</groupId>
			<artifactId>poi</artifactId>
			<version>3.9</version>
		</dependency>
		
		<dependency>
			<groupId>org.apache.poi</groupId>
			<artifactId>poi-ooxml</artifactId>
			<version>3.9</version>
		</dependency>
		
		<dependency>
			<groupId>org.apache.poi</groupId>
			<artifactId>poi-ooxml-schemas</artifactId>
			<version>3.9</version>
		</dependency>
		
		<dependency>
		    <groupId>org.apache.xmlbeans</groupId>
		    <artifactId>xmlbeans</artifactId>
		    <version>2.3.0</version>
		</dependency>
		
		
		

		<!-- mybatis end -->


		<!--GENERALUTILSbegin -->
		
		<dependency>
			<groupId>commons-io</groupId>
			<artifactId>commons-io</artifactId>
			<version>1.3.2</version>
		</dependency>
		
		<!-- weixin msg 导入本地jar包
		<dependency>  
		    <groupId>com.cmf.weixin</groupId>  
		    <artifactId>weixin-msg</artifactId>  
		    <version>1.0.0</version>  
		    <scope>system</scope>
		    <systemPath>${project.basedir}/lib/WeixinLibrary.jar</systemPath>  
		</dependency> -->
		
		<!-- <dependency>
			<groupId>com.cmf.weixin</groupId>
			<artifactId>weixin-msg</artifactId>
			<version>1.0.0</version>
		</dependency> -->
		
		<dependency>
		  <groupId>com.cmf.weixin</groupId>
		  <artifactId>weixin-msg</artifactId>
		  <version>1.2.1</version>
		</dependency>
		
		
		<!--GENERALUTILSend -->

		<!-- jetty -->
		<dependency>
			<groupId>org.eclipse.jetty.aggregate</groupId>
			<artifactId>jetty-webapp</artifactId>
			<version>${jetty.version}</version>
			<scope>test</scope>
			<exclusions>
				<exclusion>
					<groupId>org.eclipse.jetty.orbit</groupId>
					<artifactId>javax.servlet</artifactId>
				</exclusion>
			</exclusions>			
		</dependency>
		<dependency>
		  <groupId>org.eclipse.jetty.orbit</groupId>
		  <artifactId>org.apache.taglibs.standard.glassfish</artifactId>
		  <version>1.2.0.v201112081803</version>
		</dependency>

		<dependency>
			<groupId>org.eclipse.jetty</groupId>
			<artifactId>jetty-jsp</artifactId>
			<version>${jetty.version}</version>
			<scope>test</scope>
			<exclusions>
				<exclusion>
					<groupId>org.eclipse.jetty.orbit</groupId>
					<artifactId>javax.servlet</artifactId>
				</exclusion>
			</exclusions>			
		</dependency>
		
		<dependency>
			<groupId>org.eclipse.jetty.orbit</groupId>
			<artifactId>javax.servlet</artifactId>
			<version>2.5.0.v201103041518</version>
			<scope>provided</scope>
		</dependency>		
		<!-- jetty end -->

		<!-- spring begin -->
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-web</artifactId>
			<version>${spring.version}</version>
		</dependency>
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-tx</artifactId>
			<version>${spring.version}</version>
			<exclusions>
				<exclusion>
					<groupId>*</groupId>
				</exclusion>
			</exclusions>
		</dependency>


		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-jdbc</artifactId>
			<version>${spring.version}</version>
			<exclusions>
				<exclusion>
					<groupId>*</groupId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-webmvc</artifactId>
			<version>${spring.version}</version>
		</dependency>
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-oxm</artifactId>
			<version>${spring.version}</version>
		</dependency>
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-core</artifactId>
			<version>${spring.version}</version>
			<exclusions>
				<exclusion>
					<groupId>commons-logging</groupId>
					<artifactId>commons-logging</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-beans</artifactId>
			<version>${spring.version}</version>
		</dependency>
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-context</artifactId>
			<version>${spring.version}</version>
		</dependency>
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-expression</artifactId>
			<version>${spring.version}</version>
		</dependency>
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-aop</artifactId>
			<version>${spring.version}</version>
			<exclusions>
				<exclusion>
					<groupId>commons-logging</groupId>
					<artifactId>commons-logging</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-context-support</artifactId>
			<version>${spring.version}</version>
		</dependency>

		<!-- spring end -->

		<dependency>
			<groupId>c3p0</groupId>
			<artifactId>c3p0</artifactId>
			<version>0.9.1.2</version>
		</dependency>

		<dependency>
			<groupId>ojdbcJdk16</groupId>
			<artifactId>ojdbcJdk16</artifactId>
			<version>1.0.0</version>
		</dependency>

		<dependency>
			<groupId>bouncycastle</groupId>
			<artifactId>bcprov-jdk16</artifactId>
			<version>140</version>
		</dependency>
		<dependency>
			<groupId>dom4j</groupId>
			<artifactId>dom4j</artifactId>
			<version>1.6.1</version>
		</dependency>
		<dependency>
			<groupId>jcommon</groupId>
			<artifactId>jcommon</artifactId>
			<version>0.9.3</version>
		</dependency>
		<dependency>
			<groupId>org.opensymphony.quartz</groupId>
			<artifactId>quartz-all</artifactId>
			<version>1.6.1</version>
		</dependency>
		<dependency>
			<version>2.1.1</version>
			<groupId>opensymphony</groupId>
			<artifactId>oscache</artifactId>
		</dependency>
		<dependency>
			<version>1.9.11</version>
			<groupId>org.codehaus.jackson</groupId>
			<artifactId>jackson-mrbean</artifactId>
		</dependency>


		<dependency>
			<groupId>jackson</groupId>
			<artifactId>jackson-all</artifactId>
			<version>1.9.11</version>
		</dependency>

		
		<dependency>
			<groupId>org.apache.httpcomponents</groupId>
			<artifactId>httpclient</artifactId>
			<version>4.0.1</version>
		</dependency>
		<dependency>
		  <groupId>org.apache.httpcomponents</groupId>
		  <artifactId>httpcore</artifactId>
		  <version>4.0.1</version>
		</dependency>
		<dependency>    
			<groupId>org.apache.taglibs</groupId>
			<artifactId>taglibs-standard-impl</artifactId>
			<version>1.2.1</version>
		</dependency>

		<!-- <dependency>
			<groupId>com.cmwa.ec.base</groupId>
			<artifactId>cmwa-base</artifactId>
			<version>1.0.0</version>
		</dependency> -->
		
		<dependency>
			<groupId>com.cmwa.ec.base</groupId>
			<artifactId>cmwa-base</artifactId>
			<version>2.0.0</version>
		</dependency>
		
		
		<!-- LOGGING begin -->
		<dependency>
			<groupId>com.cmwa.ec.log</groupId>
			<artifactId>cmwa-logger</artifactId>
			<version>2.0.0</version>
		</dependency>
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-api</artifactId>
			<version>${slf4j.version}</version>
		</dependency>
		<dependency>
			<groupId>ch.qos.logback</groupId>
			<artifactId>logback-classic</artifactId>
			<version>${logback.version}</version>
		</dependency>
		<dependency>
			<groupId>ch.qos.logback</groupId>
			<artifactId>logback-core</artifactId>
			<version>${logback.version}</version>
		</dependency>
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>log4j-over-slf4j</artifactId>
			<version>${slf4j.version}</version>
		</dependency>
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>jcl-over-slf4j</artifactId>
			<version>${slf4j.version}</version>
		</dependency>
		<dependency>
			<groupId>commons-logging</groupId>
			<artifactId>commons-logging</artifactId>
			<version>1.1.3</version>
		</dependency>
		<dependency>
			<groupId>commons-codec</groupId>
			<artifactId>commons-codec</artifactId>
			<version>1.9</version>
		</dependency>
		<!-- LOGGING end -->
		
		
		<dependency>
			<groupId>com.cmwa.ec.message</groupId>
			<artifactId>cmwa-message-facade</artifactId>
			<version>1.0.0</version>
		</dependency>
		<dependency>
			<groupId>com.cmwa.ec.user</groupId>
			<artifactId>cmwa-user-facade</artifactId>
			<version>1.0.0</version>
		</dependency>
		<dependency>
		  <groupId>com.cmwa.ec.query</groupId>
		  <artifactId>cmwa-query-facade</artifactId>
		  <version>2.0.0</version>
		</dependency>
		<dependency>
		  <groupId>com.cmwa.ec.trade</groupId>
		  <artifactId>cmwa-trade-facade</artifactId>
		  <version>2.0.0</version>
		</dependency>
		
		<!-- json jar  start -->
		<dependency>
			<groupId>net.sf.json</groupId>
			<artifactId>json-lib</artifactId>
			<version>jdk14-2.4</version>
			<classifier>jdk14</classifier>
		</dependency>
		<!-- 
		<dependency>
			<groupId>org.apache.commons</groupId>
			<artifactId>commons-lang3</artifactId>
			<version>3.1</version>
		</dependency>
		 -->		
		<dependency>
		  <groupId>commons-lang</groupId>
		  <artifactId>commons-lang</artifactId>
		  <version>2.0</version>
		</dependency>
		<dependency>
		  <groupId>net.sf.ezmorph</groupId>
		  <artifactId>ezmorph</artifactId>
		  <version>1.0.3</version>
		</dependency>
		<dependency>
		  <groupId>commons-collections</groupId>
		  <artifactId>commons-collections</artifactId>
		  <version>3.2.1</version>
		</dependency>
		<dependency>
		  <groupId>commons-beanutils</groupId>
		  <artifactId>commons-beanutils</artifactId>
		  <version>20030211.134440</version>
		</dependency>
		<!-- json jar  end -->
		
		<!-- jstl jar  start -->
		<dependency>
		  <groupId>jstl</groupId>
		  <artifactId>jstl</artifactId>
		  <version>1.2</version>
		</dependency>
		<dependency>
		  <groupId>taglibs</groupId>
		  <artifactId>standard</artifactId>
		  <version>1.1.2</version>
		</dependency>
		<!-- jstl jar  end -->
		
		<dependency>
			<groupId>aopalliance</groupId>
			<artifactId>aopalliance</artifactId>
			<version>1.0</version>
		</dependency>
		<dependency>
			<groupId>com.alibaba</groupId>
			<artifactId>fastjson</artifactId>
			<version>1.2.58</version>
		</dependency>
		<dependency>
			<groupId>jaxen</groupId>
			<artifactId>jaxen</artifactId>
			<version>1.1.6</version>
		</dependency>
		
		<!-- 新增hibernate validation校验所需要的jar包  begin -->
		<dependency>
		    <groupId>org.hibernate</groupId>
		    <artifactId>hibernate-validator</artifactId>
	    	<version>5.1.3.Final</version> 
	    </dependency>
	    <dependency>  
		    <groupId>javax.validation</groupId>  
		    <artifactId>validation-api</artifactId>  
		    <version>1.1.0.Final</version>  
		</dependency>  
		<dependency>  
		    <groupId>org.jboss.logging</groupId>  
		    <artifactId>jboss-logging</artifactId>  
		    <version>3.1.3.GA</version>  
		</dependency> 
		<dependency>  
		    <groupId>com.fasterxml</groupId>  
		    <artifactId>classmate</artifactId>  
		    <version>1.0.0</version>  
		</dependency> 
		<dependency>
		    <groupId>org.glassfish.web</groupId>
		    <artifactId>el-impl</artifactId>
		    <version>2.2</version>
		</dependency>
	    <!-- 新增hibernate validation校验所需要的jar包  end -->
	    
	</dependencies>
	
	<build>
		<!-- <defaultGoal>install</defaultGoal> -->
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-jar-plugin</artifactId>
				<configuration>
					<includes>
						<include>**/*.class</include>
					</includes>
					<!--<excludes><exclude>**/test/**/*.class</exclude></excludes> -->
				</configuration>
			</plugin>

			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-resources-plugin</artifactId>
				<version>2.6</version>
			</plugin>

			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-install-plugin</artifactId>
				<version>2.4</version>
			</plugin>

			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-clean-plugin</artifactId>
				<version>2.5</version>
			</plugin>

			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-dependency-plugin</artifactId>
				<version>2.8</version>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.0</version>
				<configuration>
					<source>1.6</source>
					<target>1.6</target>
					<encoding>GBK</encoding>
					<verbal>true</verbal>
					<!--<compilerArguments>  
                        <verbose />  
                        <bootclasspath>${java.home}/lib/rt.jar;${java.home}/lib/jce.jar</bootclasspath>  
                    </compilerArguments>-->
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-antrun-plugin</artifactId>
				<configuration>
					<tasks>
						<delete dir="${target.path}/${project.artifactId}" />
					</tasks>
				</configuration>
				<executions>
					<execution>
						<id>deleteOldDir</id>
						<phase>prepare-package</phase>
						<goals>
							<goal>run</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-assembly-plugin</artifactId>
				<version>2.4</version>
				<configuration>
					<finalName>${project.artifactId}</finalName>
					<appendAssemblyId>false</appendAssemblyId>
					<outputDirectory>${target.path}</outputDirectory>
					<descriptors>
						<descriptor>assembly.xml</descriptor>
					</descriptors>
					<encoding>${project.build.sourceEncoding}</encoding>
					<updateOnly>true</updateOnly>
				</configuration>
				<executions>
					<execution>
						<id>make-assembly</id>
						<phase>package</phase>
						<goals>
							<goal>single</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
			<!-- mvn install时候，打包 -->
			<!-- <plugin>  
	        	<groupId>org.apache.maven.plugins</groupId>  
	        	<artifactId>maven-surefire-plugin</artifactId>  
	        	<version>2.18.1</version>  
	        	<configuration>  
	          		<skipTests>true</skipTests>
	        	</configuration>
	      	</plugin> -->
		</plugins>
	</build>

	<artifactId>cmwa-wx-webapp</artifactId>
</project>
