#------------------------------
# AD\u57DF\u9A8C\u8BC1\u914D\u7F6E\u6587\u4EF6 WinAD\u914D\u7F6E\u4FE1\u606F
#------------------------------
WINAD_URL = ldap://172.18.0.20:389/dc=cmf-int-dc,dc=com

WINAD_DOMAIN = @cmf-int-dc.com

WINAD_JNDI = com.sun.jndi.ldap.LdapCtxFactory