jdbc.key=8a!2e4b4%1b6e2&ba5.-011b?720f-=+

#ecuser service
jdbc.ecuser.driverClassName=oracle.jdbc.driver.OracleDriver
jdbc.ecuser.url=jdbc:oracle:thin:@192.168.8.201:1521:DEVCMFOLTP
jdbc.ecuser.username=waecuser
#9BD9ED7B142F98C5C1046166447C4B56=cmf+2011
jdbc.ecuser.password=9BD9ED7B142F98C5C1046166447C4B56
jdbc.ecuser.acquireIncrement=1
jdbc.ecuser.maxIdleTime=20000
jdbc.ecuser.maxPoolSize=2
jdbc.ecuser.minPoolSize=2
jdbc.ecuser.initialPoolSize=2
jdbc.ecuser.checkoutTimeout=20000

#crm
jdbc.crm.driverClassName=oracle.jdbc.driver.OracleDriver
jdbc.crm.url=jdbc:oracle:thin:@192.168.8.200:1521:DEVCMFBP
jdbc.crm.username=crm
#9BD9ED7B142F98C5C1046166447C4B56=cmf+2011
jdbc.crm.password=9BD9ED7B142F98C5C1046166447C4B56
jdbc.crm.acquireIncrement=1
jdbc.crm.maxIdleTime=30000
jdbc.crm.maxPoolSize=2
jdbc.crm.minPoolSize=2
jdbc.crm.initialPoolSize=2
jdbc.crm.checkoutTimeout=20000  
