mail.smtp.host=192.168.6.99
mail.smtp.auth=true
mail.transport.protocol=smtp

mail.user.username=report
mail.user.password=cmf@2013

#mail.path=D://mail/2016
mail.from=report@cmfchina.com


#\u4E24\u5929\u540E\u53EF\u8D4E\u56DE\u4EFD\u989D
custom1.mail.smtp.host=192.168.6.99
custom1.mail.user.username=report
custom1.mail.user.password=cmf@2013
custom1.mail.from=report@cmfchina.com

#T\u5929\u6700\u5927\u53EF\u8D4E\u56DE\u4EFD\u989D\u63D0\u9192
custom2.mail.smtp.host=192.168.6.99
custom2.mail.user.username=report
custom2.mail.user.password=cmf@2013
custom2.mail.from=report@cmfchina.com

mail.path=/usr/local/resin/cmwa/business-attach/
