#wx
wxHost=http://192.168.8.171:17811
#pc
pcHost=http://192.168.8.182:17846


invalid_char_set='_<_>_;_$_"_+_\\_<iframe_<script_script>_iframe>_alert(_+or+_+-_-+_null%2B_%3Ciframe_%3Cscript_script%3E_iframe%3E
error_page=/login/login.shtml

ecFundElePicPre=/usr/local/webapp/cmwa-ec-webapp
ecFundElePic=/AppService/business/fundPic/

#mailPath
toMailPath=ex-chenbq@cmfchina.com
ccMailPath=ex-longyh@cmfchina.com

#resetLPassWord  unit: second
resetLPWGapTime = 60